### PR TITLE
Added a build file

### PR DESCRIPTION
**Pull request by erkantaylan**
I only tested on windows.

### CODE REVIEW

**Comment by daveyarwood** [comment]
Tried this out on OS X and it almost worked out of the box. I got this error:

```
[Errno 2] No such file or directory: 'alda'
[cmd: ['alda', 'play', '--file', '"/Users/dave/Code/alda/examples/gau.alda"']]
[dir: /Users/dave/Code/alda/examples]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

The issue was that my command-line `$PATH` is not the same as the `$PATH` that Sublime Text uses. My `alda` executable is in `/usr/local/bin`, which is not on Sublime's `$PATH`. I was able to get it working by adding `/usr/local/bin` to the `$PATH`, like so:

```
{
  "cmd": ["alda", "play","--file", "\"${file}\""],
  "selector" : "source.alda",
  "path": "/usr/local/bin:$PATH"
}
```

I don't usually use Sublime, so I'm not sure what the best way to handle this would be -- we can't account for every possible directory where the user might have his/her `alda` executable. But, I think a lot of people will have it in either one of the default directories in Sublime's `$PATH`, or in `/usr/local/bin` which is where we recommend installing Alda in the Alda README. So, adding `/usr/local/bin` will probably be sufficient in most cases.

**Comment by erinzm** [comment]
@daveyarwood huh, maybe https://github.com/int3h/SublimeFixMacPath could be useful. with packagecontrol 3.0 I could make it a dependency of this package.

**Comment by daveyarwood** [comment]
Ah, that looks promising! If you set that up as a dependency, I'll be happy
to test it.

**Comment by erinzm** [comment]
Ohhh wait, misread dependency docs. I can actually just put the FIxMacPath
code in _this_ plugin and it should be cool. I'll do that sometime soon
(I'm pretty busy tho), PRs are welcome :)

**Comment by daveyarwood** [comment]
I wasn't able to get FixMacPath to work, either by copying FixPath.py into the same working directory as the other files (`~/Library/Application Support/Sublime Text 3/Packages/Alda - Local`), or by installing FixMacPath through Package Control.

**Comment by daveyarwood** [comment]
I tried [this fork](https://github.com/Gr1N/SublimeFixMacEnv) too... no dice.

**Comment by erinzm** [comment]
@erkantaylan Since this is independent of the OSX $PATH issues, I'm merging this since it's pretty useful, and it currently works on everything except OSX.

**Pull request merged**
